name: Test labels

on:
  workflow_dispatch:
   inputs:
    application: 
     required: false
     type: choice 
     options: 
      - first
      - second

jobs:
 open_issue:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v3
   - name: Open issue
     id: create-issue
     uses: JasonEtco/create-an-issue@v2.9.1
     env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     with:
      assignees: ${{ github.actor }}
      filename: .github/issues/deployment_request.md
   - name: Label issue
     run: gh issue edit "$NUMBER" --add-label "$LABELS"
     env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_REPO: ${{ github.repository }}
      NUMBER: ${{ steps.create-issue.outputs.number }}
      LABELS: triage, ${{ inputs.application }}
   
