name: Test labels

on:
  workflow_dispatch:
   inputs:
    application: 
     required: false
     type: choice 
     options: 
      - first
      - second

jobs:
 open_issue:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v3
   - name: Open issue
     uses: JasonEtco/create-an-issue@v2
     env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       SERVICE_NAME: ${{ inputs.application }}
     with:
      assignees: ${{ github.actor }}
      filename: .github/issues/deployment_request.md
   
